### ISSUE TITLE
Certificates are not updated on certificate rotation

### ISSUE THREAD

**Issue by mmkay** [canonical/cos-lib#89]
### Bug Description

When a certificate expires, new certificate doesn't seem to be copied over to the worker or coordinator charm container. This causes to stop serving traffic, even though charms are in `active/idle`.

### To Reproduce

Deploy the following bundle:

```
bundle: kubernetes
applications:
  grafana:
    charm: grafana-k8s
    channel: latest/edge
    revision: 119
    base: ubuntu@20.04/stable
    resources:
      grafana-image: 70
      litestream-image: 45
    scale: 1
    constraints: arch=amd64
    storage:
      database: kubernetes,1,1024M
    trust: true
  minio:
    charm: minio
    channel: latest/edge
    revision: 376
    base: ubuntu@20.04/stable
    resources:
      oci-image: 545
    scale: 1
    options:
      access-key: accesskey
      secret-key: secretkey
    constraints: arch=amd64
    storage:
      minio-data: kubernetes,1,10240M
    trust: true
  s3:
    charm: s3-integrator
    channel: latest/edge
    revision: 59
    scale: 1
    options:
      bucket: tempo
    constraints: arch=amd64
    trust: true
  ssc:
    charm: self-signed-certificates
    channel: latest/edge
    revision: 200
    scale: 1
    options:
      certificate-validity: 15m
    constraints: arch=amd64
    trust: true
  tempo:
    charm: tempo-coordinator-k8s
    channel: latest/edge
    revision: 25
    resources:
      nginx-image: 5
      nginx-prometheus-exporter-image: 3
    scale: 1
    constraints: arch=amd64
    storage:
      data: kubernetes,1,1024M
    trust: true
  worker:
    charm: tempo-worker-k8s
    channel: latest/edge
    revision: 34
    resources:
      tempo-image: 3
    scale: 1
    constraints: arch=amd64
    storage:
      data: kubernetes,1,1024M
    trust: true
relations:
- - s3:s3-credentials
  - tempo:s3
- - ssc:certificates
  - tempo:certificates
- - tempo:tracing
  - ssc:tracing
- - tempo:tempo-cluster
  - worker:tempo-cluster
- - minio:grafana-dashboard
  - grafana:grafana-dashboard
- - self-signed-certificates:certificates
  - grafana:certificates
- - ssc:send-ca-cert
  - grafana:receive-ca-cert
- - tempo:grafana-dashboard
  - grafana:grafana-dashboard
- - tempo:grafana-source
  - grafana:grafana-source
- - tempo:tracing
  - grafana:tracing
```

and configure s3-integrator to work with access and secret key:

```
MODEL_NAME=$(juju models --format yaml | yq .current-model)
juju run s3/0 sync-s3-credentials access-key=accesskey secret-key=secretkey
juju config s3 endpoint=minio-0.minio-endpoints.$MODEL_NAME.svc.cluster.local:9000
```

also use the deploy_minio script to provision the bucket.

Wait 15 minutes for the certificate to expire.

### Environment

`latest/edge` track for all the charms.

juju status:
```
$ juju status
Model        Controller  Cloud/Region        Version  SLA          Timestamp
welcome-k8s  microk8s    microk8s/localhost  3.5.3    unsupported  12:04:45+02:00

App                       Version                Status  Scale  Charm                     Channel      Rev  Address         Exposed  Message
grafana-k8s               9.5.3                  active      1  grafana-k8s               latest/edge  119  10.152.183.98   no       
minio                     res:oci-image@220b31a  active      1  minio                     latest/edge  376  10.152.183.101  no       
s3                                               active      1  s3-integrator             latest/edge   59  10.152.183.106  no       
self-signed-certificates                         active      1  self-signed-certificates  latest/edge  200  10.152.183.225  no       
tempo-coordinator-k8s                            active      1  tempo-coordinator-k8s     latest/edge   25  10.152.183.55   no       metrics-generator disabled. Add a relation over send-remote-write
tempo-worker-k8s          ...                    active      1  tempo-worker-k8s          latest/edge   34  10.152.183.160  no       metrics-generator disabled. No prometheus remote-write relation configured on the coordinator

Unit                         Workload  Agent  Address       Ports          Message
grafana-k8s/0*               active    idle   10.1.157.102                 
minio/0*                     active    idle   10.1.157.92   9000-9001/TCP  
s3/0*                        active    idle   10.1.157.90                  
self-signed-certificates/0*  active    idle   10.1.157.93                  
tempo-coordinator-k8s/0*     active    idle   10.1.157.98                  metrics-generator disabled. Add a relation over send-remote-write
tempo-worker-k8s/0*          active    idle   10.1.157.99                  metrics-generator disabled. No prometheus remote-write relation configured on the coordinator
```

### Relevant log output

```shell
$ juju show-status-log tempo-coordinator-k8s/0
Time                        Type       Status     Message
04 Oct 2024 11:45:57+02:00  juju-unit  executing  running grafana-dashboard-relation-changed hook for grafana-k8s/0
04 Oct 2024 11:45:58+02:00  juju-unit  executing  running grafana-source-relation-joined hook for grafana-k8s/0
04 Oct 2024 11:46:00+02:00  juju-unit  executing  running grafana-source-relation-changed hook for grafana-k8s/0
04 Oct 2024 11:46:02+02:00  juju-unit  executing  running tracing-relation-changed hook
04 Oct 2024 11:46:04+02:00  juju-unit  executing  running tracing-relation-joined hook for grafana-k8s/0
04 Oct 2024 11:46:06+02:00  juju-unit  executing  running tracing-relation-changed hook for grafana-k8s/0
04 Oct 2024 11:46:07+02:00  juju-unit  idle       
04 Oct 2024 11:46:22+02:00  juju-unit  executing  running secret-expired hook for crvrelvmp25c77snb1l0/1
04 Oct 2024 11:46:23+02:00  juju-unit  idle       
04 Oct 2024 11:46:25+02:00  juju-unit  executing  running certificates-relation-changed hook
04 Oct 2024 11:46:28+02:00  juju-unit  idle       
04 Oct 2024 11:51:22+02:00  juju-unit  executing  running secret-expired hook for crvrelvmp25c77snb1l0/1
04 Oct 2024 11:51:23+02:00  juju-unit  idle       
04 Oct 2024 11:56:25+02:00  juju-unit  executing  running secret-expired hook for crvrisvmp25c77snb1m0/1
04 Oct 2024 11:56:26+02:00  juju-unit  idle       
04 Oct 2024 11:56:27+02:00  juju-unit  executing  running certificates-relation-changed hook
04 Oct 2024 11:56:29+02:00  juju-unit  idle       
04 Oct 2024 12:01:25+02:00  juju-unit  executing  running secret-expired hook for crvrisvmp25c77snb1m0/1
04 Oct 2024 12:01:26+02:00  workload   active     metrics-generator disabled. Add a relation over send-remote-write
04 Oct 2024 12:01:26+02:00  juju-unit  idle   

$ juju debug-log
unit-tempo-worker-k8s-0: 12:01:27 ERROR unit.tempo-worker-k8s/0.juju-log tempo-cluster:5: Exception while exporting Span batch.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-tempo-worker-k8s-0/charm/venv/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/var/lib/juju/agents/unit-tempo-worker-k8s-0/charm/venv/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/var/lib/juju/agents/unit-tempo-worker-k8s-0/charm/venv/urllib3/connection.py", line 730, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "/var/lib/juju/agents/unit-tempo-worker-k8s-0/charm/venv/urllib3/connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "/var/lib/juju/agents/unit-tempo-worker-k8s-0/charm/venv/urllib3/util/ssl_.py", line 469, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/var/lib/juju/agents/unit-tempo-worker-k8s-0/charm/venv/urllib3/util/ssl_.py", line 513, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1100, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1371, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1007)
```

**Comment by PietroPasotti** [comment]
I get a different but related error:
the coordinator errors out with
![image](https://github.com/user-attachments/assets/27d77d3f-4e4b-4e35-b1be-b3f35d7fe1b0)

and the worker is stuck trying to restart and crashes

**Comment by PietroPasotti** [comment]
It seems like a fix in the tls-certificates lib has fixed the issue

![image](https://github.com/user-attachments/assets/4afb8f31-ad2a-430a-ab73-503d742a37de)

should go away with a lib update

**Comment by PietroPasotti** [comment]
@mmkay if you can confirm, we'll close this

**Comment by mmkay** [comment]
Confirmed to still work after cert rotation:

```
$ juju show-status-log tempo-coordinator-k8s/0
Time                        Type       Status     Message
18 Oct 2024 19:38:30+04:00  juju-unit  executing  running certificates-relation-created hook
18 Oct 2024 19:38:32+04:00  juju-unit  executing  running tracing-relation-created hook
18 Oct 2024 19:38:34+04:00  juju-unit  executing  running certificates-relation-joined hook for self-signed-certificates/0
18 Oct 2024 19:38:37+04:00  juju-unit  executing  running tracing-relation-changed hook
18 Oct 2024 19:38:40+04:00  juju-unit  executing  running certificates-relation-changed hook for self-signed-certificates/0
18 Oct 2024 19:38:42+04:00  juju-unit  executing  running tracing-relation-joined hook for self-signed-certificates/0
18 Oct 2024 19:38:44+04:00  juju-unit  executing  running ingress-relation-changed hook
18 Oct 2024 19:38:47+04:00  juju-unit  executing  running tracing-relation-changed hook for self-signed-certificates/0
18 Oct 2024 19:38:50+04:00  juju-unit  idle       
18 Oct 2024 19:38:52+04:00  juju-unit  executing  running certificates-relation-changed hook
18 Oct 2024 19:38:57+04:00  juju-unit  idle       
18 Oct 2024 19:39:14+04:00  juju-unit  executing  running send-remote-write-relation-changed hook for prometheus/0
18 Oct 2024 19:39:18+04:00  juju-unit  idle       
18 Oct 2024 19:39:26+04:00  juju-unit  executing  running logging-relation-changed hook for loki/0
18 Oct 2024 19:39:31+04:00  juju-unit  idle       
18 Oct 2024 19:52:11+04:00  juju-unit  executing  running secret-expired hook for cs98247mp25c77qpqbbg/1
18 Oct 2024 19:52:18+04:00  juju-unit  idle       
18 Oct 2024 19:52:21+04:00  juju-unit  executing  running certificates-relation-changed hook
18 Oct 2024 19:52:27+04:00  workload   active     Degraded.
```

![Screenshot from 2024-10-18 17-55-35](https://github.com/user-attachments/assets/ea9a164a-42a6-4481-aa2a-326eb1803d5d)

(time in grafana is 2h earlier, timezone jumps, but it was in fact after cert rotation)
